# building stage
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# compile
RUN npm run build

# runner stage
FROM node:22-alpine AS runner

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
# Install only production dependencies (if any)
RUN npm install --omit=dev

CMD [ "node", "dist/index.js" ]